version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: assign-me-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assign_me_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - assign-me-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: assign-me-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - assign-me-network

volumes:
  postgres_data:

networks:
  assign-me-network:
    driver: bridge 